- name : play level var
  hosts : localhost
  vars :
    URL : example.play.com
  tasks :
    - name : Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name : variable from a file
  hosts : localhost
  vars_files:
    - demo.var.yml
  tasks :
    - name : print url
      ansible.builtin.debug:
        msg : URL = {{ URL }}


