#playlevel variables

- name : Intro to playlevel Var
  hosts: localhost
  vars :
    URL : ZEESHAN@DEVOPS.COM
  tasks :
    - name : print URL
      ansible.builtin.debug:
        msg : URL = {{ URL }}

#Variable from a file

- name : variable from another file and access it in our play
  hosts : localhost
  vars_files:
    - Demo.yml
  tasks :
    - name : print url from demo.url file
      ansible.builtin.debug:
        msg : URL= {{ URL }}

#Tasl Level Variables

- name : Task Level Vars
  hosts : localhost
  tasks :
    - name : print URL AT TASK LEVEL
      ansible.builtin.debug:
        msg : URL = {{ URL }}
      vars:
        URL : ZEESHAN@DEVOPS.COM

#INVENTORY LEVEL VARS

- name : Intro to Inventory level vars
  hosts : localhost
  tasks :
    - name : print var from inventory file
      ansible.builtin.debug:
        msg: URL {{ URL }}
