- name : play level var
  hosts : localhost
  vars :
    URL : example.play.com
  tasks :
    - name : Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}
# The below play is access a Var From a File
- name : variable from a file
  hosts : localhost
  vars_files:
    - demo.var.yml
  tasks :
    - name : print url
      ansible.builtin.debug:
        msg : URL = {{ URL }}

# The below play is declare  a Var From the task level

- name : declare a var at Task level
  hosts : localhost
  tasks :
    - name : print url
      ansible.builtin.debug:
        msg : URL = {{ URL }}
      vars:
        URL : tasklevel.var.com

# The below play is declare  a Var From the Inventory file

- name : declare a var from Inventory
  hosts : localhost
  tasks :
    - name: print url
      ansible.builtin.debug:
        msg : URL = {{ URL }}

 # Ansible runtime variables

- name : Register Variable
  hosts : localhost
  tasks :
    - name : run uptime command
      ansible.builtin.shell : uptime
      register : OUTPUT_UPTIME
    - name : print the output of Uptime command
      ansible.builtin.debug :
        msg : {{"OUTPUT_UPTIME"}}