#ANSIBLE PRE-DEFINED VARIABLES

- name : Facts
  hosts : localhost
  tasks :
    - name : Print HostName
      ansible.builtin.debug:
        msg : HostName = {{ ansible_hostname }}
    - name: Print FQDN
      ansible.builtin.debug:
        msg:  "{{ ansible_fqdn }}"