- name : Register variables
  hosts : localhost
  tasks :
    - name : Run Linux-shell Commands
      ansible.builtin.shell: uptime
      register : output

    - name : Print out put of Linux shell command
      ansible.builtin.debug:
        msg : "{{ output }}"