- name : Facts
  hosts : localhost
  tasks :
    - name : printing Hostname
      ansible.builtin.debug :
        msg : HOSTNAME = {{ ansible_hostname }}

    - name: Print date and time
      ansible.builtin.debug :
        msg : Date_Time = {{ ansible_date_time }}

#Ansible Run time Commands--1.from task o/p (register)  2. set a variable using task (set_fact)

- name : Run Time Variables
  hosts : localhost
  tasks :
    - name : Run Uptime command
      ansible.builtin.shell : ls
      register : Shell_output
    - name : Print ls command output
      ansible.builtin.debug :
        msg : "{{Shell_output.stdout}}"

#Storing a variable in standard name

- name : Run Time Variables
  hosts : localhost
  tasks :
    - name : Run Uptime command
      ansible.builtin.shell : ls
      register : Shell_output
    - name : storing a variable in a standard name
      ansible.builtin.set_fact :
        UPTIME : "{{Shell_output.stdout}}"

    - name : print out put of shell command
      ansible.builtin.debug:
        msg : "{{UPTIME}}"


