- name : Facts
  hosts : localhost
  tasks :
    - name : printing Hostname
      ansible.builtin.debug :
        msg : HOSTNAME = {{ ansible_hostname }}

    - name: Print all available facts
      ansible.builtin.debug :
        msg : AVAIL_FACTS = {{ ansible_facts }}