- name : Facts
  hosts : localhost
  tasks :
    - name : printing Hostname
      ansible.builtin.debug :
        msg : HOSTNAME = {{ ansible_hostname }}

    - name: Print date and time
      ansible.builtin.debug :
        msg : Date_Time = {{ ansible_date_time }}