- name : Play level vars
  hosts : localhost
  vars :
    URL : example.playvar.com
  tasks :
    - name : print URL
      ansible.builtin.debug :
        msg : URL = {{URL}}


- name : Variable from a file
  hosts : localhost
  vars_files :
    - demo.var.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}


- name: declare a var at Task level
  hosts: localhost
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasklevel.var.com



