- name : Play level vars
  hosts : localhost
  vars :
    URL : example.playvar.com
  tasks :
    - name : print URL
      ansible.builtin.debug :
        msg : URL = {{URL}}


- name : Variable from a file
  hosts : localhost
  vars_files :
    - demo.var.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}


- name : Task level variable
  hosts : localhost
  tasks :
    - name : printing url from task level var
      ansible.builtin.debug :
        msg : URL = {{URL}}
        vars :
          URL : Tasklevel.var.com



